const data = {
    data: [
        {
            title: "EasyLink",
            mustsee: false,
            descrption: "A resource to share links easily.",
            url: "https://piyushiso.github.io/tools/easylink/",
            tools: "HTML, CSS, JS",
            tags: "random, tools",
        },
        {
            title: "WRS.app",
            mustsee: false,
            descrption: "An app that helped me record my daily work few years ago.",
            url: "https://piyushiso.github.io/app/wrs.app/",
            tools: "HTML, CSS, JS",
            tags: "random, tools, work",
        },
        {
            title: "Perry the Platypus",
            mustsee: true,
            descrption: "Helping Dr. Heinz Doofenshmirtz (or atleast I think so).",
            url: "https://piyushiso.github.io/random/perry/",
            tools: "HTML, CSS, JS",
            tags: "random",
        },
        {
            title: "Profile | BCA & BIM (2080)",
            mustsee: false,
            descrption: "An app that helped us manage a lowkey interview profiles for the students of the BCA & BIM (Batch of 2080).",
            url: "https://piyushiso.github.io/random/perry/",
            tools: "HTML, CSS, JS, JSON",
            tags: "random, app, work, profile, portfolio",
        },
        {
            title: "Pancake Flip",
            mustsee: true,
            descrption: "An educational game that I developed back when I was a part of ChimpVine (Danson Solutions) as an Associate Game Developer. Also kudos to my teammate for the awesome art assets!",
            url: "https://play.google.com/store/apps/details?id=com.chimpvine.pancakeflip&hl=en_US&pli=1",
            tools: "Unity, C#",
            tags: "random, game, game development, educational",
        },
        {
            title: "Profiler",
            mustsee: false,
            descrption: "An app developed to display the students' data for the Career Expo 2024 (HSMSS). Developed using React JS and uploaded via Vercel.",
            url: "https://profiler-kappa.vercel.app",
            tools: "HTML, CSS, JS, React JS, Vercel",
            tags: "random, app, work, profile, portfolio",
        },
        {
            title: "www.nishchalbaniya.com.np",
            mustsee: true,
            descrption: "Developed a portfolio website of Mr. Nishchal Baniya along with my team (Lv. 1 Alchemy).",
            url: "https://profiler-kappa.vercel.app",
            tools: "HTML, CSS, JS",
            tags: "random, profile, portfolio, work",
        },
        {
            title: "EEVEELUTIONS",
            mustsee: false,
            descrption: "Eeveelutions, because why not? A random project developed to showcase all the Eeveelutions from the Pokemon franchise. This project was developed as a part of the Odyssey-30 days challenge (I gave up on day 1).",
            url: "https://piyushiso.github.io/odyssey/day-1/",
            tools: "HTML, CSS, JS",
            tags: "random",
        },
        {
            title: "Worst UX Ever",
            mustsee: false,
            descrption: "A website developed to demonstrate the Worst UX competition scenario (organized along with the IT Club of HSMSS), solely to showcase the worst UX practices & for the fun of it.",
            url: "https://piyushiso.github.io/random/worstuxever/",
            tools: "HTML, CSS, JS",
            tags: "random, ux, event, it-club",
        },
        {
            title: "Acoustic Fest | 2022",
            mustsee: false,
            descrption: "A website developed to support the concept and initiation of the first ever Acoustic Fest of HSMSS, organized as a part of the HSMSS Fest (2022).",
            url: "https://piyushiso.github.io/event/acousticfest/",
            tools: "HTML, CSS, JS",
            tags: "random, acoustic-fest, event",
        },
        {
            title: "Portfolio Website",
            mustsee: false,
            descrption: "A website developed to assist students complete their portfolio project. PS: I don't have any web-portfolio of my own though.",
            url: "https://piyushiso.github.io/class/portfolio/",
            tools: "HTML, CSS, JS",
            tags: "random, project, class, portfolio, profile",
        },
        {
            title: "SUS-ITUATION",
            mustsee: false,
            descrption: "A random game created during lockdown to pass time, and match the trend. Note: The names presented are fictional and doesn't represent any real person.",
            url: "https://piyushiso.github.io/game/sus-ituation.game/",
            tools: "HTML, CSS, JS",
            tags: "random, game",
        },
        {
            title: "BINGO TABLE",
            mustsee: false,
            descrption: "A normal bingo generator for a quick game. Developed solely so that my students won't waste papers to create bingo tables manually.",
            url: "https://piyushiso.github.io/odyssey/day-6/",
            tools: "HTML, CSS, JS",
            tags: "random, game",
        },
        {
            title: "DOTA 2 | HEROES",
            mustsee: false,
            descrption: "A normal limited DOTA 2 heroes visualizer.",
            url: "https://piyushiso.github.io/odyssey/day-2/",
            tools: "HTML, CSS, JS",
            tags: "random, game",
        },
        {
            title: "Everything Data",
            mustsee: true,
            descrption: "My data science project, that does basic cleaning, visualization and analysis using DanfoJS library.",
            url: "https://piyushiso.github.io/app/everythingdata/",
            tools: "HTML, CSS, Bootstrap, JS, DanfoJS",
            tags: "random, data, data-science, project",
        },
        {
            title: "Day & Night",
            mustsee: false,
            descrption: "A project that would have showed the day and night or something like that (Never completed).",
            url: "https://piyushiso.github.io/random/daynight/",
            tools: "HTML, CSS",
            tags: "random, incomplete",
        },
        {
            title: "Website w. Cheats",
            mustsee: false,
            descrption: "A project that is incomplete, and I don't even remember what it was about.",
            url: "https://piyushiso.github.io/random/cheats/",
            tools: "HTML, CSS, Bootstrap",
            tags: "random, incomplete",
        },
        {
            title: "XSURL",
            mustsee: false,
            descrption: "A URL shortner app, that works (The project is not hosted though).",
            url: "https://github.com/piyushiso/XSURL/tree/main",
            tools: "HTML, CSS, JS, React, Node, SQLite",
            tags: "random, project, app, tools",
        },
        {
            title: "Quex",
            mustsee: false,
            descrption: "A question generator app, that never got completed.",
            url: "https://github.com/piyushiso/Quex",
            tools: "HTML, CSS, JS, React, Node",
            tags: "random, project, app, tools",
        },
        {
            title: "EMIS | A Simple Django CRUD App",
            mustsee: false,
            descrption: "A simple CRUD App developed using Django Framework to manage employee records.",
            url: "https://github.com/piyushiso/Kutumba-Tech/tree/main/EMIS",
            tools: "HTML, CSS, JS, Django, SQLite, POSTGRESQL",
            tags: "random, project, app",
        },
        {
            title: "PASAL | Online Shopping Site",
            mustsee: false,
            descrption: "A hardcoded online shopping site developed using PHP and MySQL as my project submission for the subject PHP. And I am hella proud of it.",
            url: "https://github.com/Piyush-Lal-Shrestha-2000/PASAL---Online-Shopping-Site",
            tools: "HTML, CSS, JS, PHP, MySQL",
            tags: "random, project, app",
        },
        {
            title: "RijuApps",
            mustsee: false,
            descrption: "Projects coded back when I was an intern @ RijuShree.",
            url: "https://github.com/Piyush-Lal-Shrestha-2000/RijuApps",
            tools: "HTML, CSS, JS, PHP, AJAX, MySQL, Wordpress",
            tags: "random, project, app",
        },
        {
            title: "Explore Nepal / ExplorePal",
            mustsee: false,
            descrption: "My first ever hackathon (Spirathon 2019, Spiralogics International - Kathmandu, Nepal) project along with my team (He-Tech-Auda). There is a lot to talk about this project & experience, but I will keep it for another time.",
            url: "https://github.com/Piyush-Lal-Shrestha-2000/ExploreNepal/tree/master/ExploreNepal",
            tools: "HTML, CSS, JS, PHP, AJAX, MySQL",
            tags: "random, project, hackathon",
        },
        {
            title: "ProjectC",
            mustsee: false,
            descrption: "Another hackathon project (Kathfoss 2020) that I had to complete solo due to unavoidable circumstances. The project timeline (yes the timeline, and not the project alone) was a time when I explored new avenues.",
            url: "https://github.com/Piyush-Lal-Shrestha-2000/ProjectC",
            tools: "HTML, CSS, JS, PHP, AJAX, MySQL",
            tags: "random, project, hackathon",
        },
        {
            title: "File-Sorter-Python-",
            mustsee: false,
            descrption: "A desktop app that sorts the contents of the folder on the basis of the file extension. My first ever Python project, and also the first time I ever used the algorithms properly.",
            url: "https://github.com/Piyush-Lal-Shrestha-2000/File-Sorter-Python-",
            tools: "Python, Tkinter",
            tags: "random, project, tools, desktop-app",
        },
        {
            title: "Searching In Excel",
            mustsee: false,
            descrption: "A web app that made searching in Excel sheets easier (I think so, or atleast it helped me during that time).",
            url: "https://github.com/Piyush-Lal-Shrestha-2000/SearchingInExcel",
            tools: "HTML, CSS, PHP",
            tags: "random, project, tools",
        },
        {
            title: "navodaya.edu.np",
            mustsee: false,
            descrption: "A website that never got completed.",
            url: "https://github.com/Piyush-Lal-Shrestha-2000/navodaya.edu.np",
            tools: "HTML, CSS, JS",
            tags: "random, project",
        },
    ]
}